don't overwrite list
problem:
assigning a list of animals to the list variable overwrites the list function, so that later in line 531 the list function is not available and raises a Type Error:
```
In [133]: list(filled_dict.keys())
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-133-a2c520b90051> in <module>
----> 1 list(filled_dict.keys())

TypeError: 'list' object is not callable
```
solution:
use another variable name instead of list